<?php
/************************************************************************/
/* ATutor                                                               */
/************************************************************************/
/* Copyright (c) 2013                                                   */
/* Sandamal S.T.R                                                       */
/*                                                                      */
/* This page is available for public to register to the system          */
/* This will generate and display the form generated by the utility     */
/************************************************************************/

$_user_location	= 'public';
define('AT_INCLUDE_PATH', '../../include/');
require (AT_INCLUDE_PATH.'vitals.inc.php');
$_custom_css = $_base_path . 'mods/hello_world/module.css'; // use a custom stylesheet
$_custom_head .= '<script type="text/javascript" src="'.AT_BASE_HREF.'mods/hello_world/sha-1factory.js"></script>';
require (AT_INCLUDE_PATH.'header.inc.php');
global $languageManager, $_config, $moduleFactory;
use PFBC\Form;
use PFBC\Element;
use PFBC\View;
?>


<script type="text/javascript">
    function encrypt_password()
    {
        document.getElementById("password_error").value="";


        err = verify_password(document.getElementById("form_password1").value, document.getElementById("form_password2").value);

        if (err.length > 0)
        {
            document.getElementById("password_error").value = err;
        }
        else
        {
            document.getElementById("form_password_hidden").value = hex_sha1(document.getElementById("form_password1").value);
        }
    }
</script>


<?php


if($_config['allow_reg'] != 1){
   $msg->addInfo('REG_DISABLED');
   header('Location: ../../index.php');
   exit;
}
//process posted data
if (isset($_POST['submit_form']))
{
    /* registration token validation */
    if (sha1($_SESSION['token']) != $_POST['registration_token']){
        //Prevent registration from any other pages other than the ATutor pages.
        //SHA1(SESSION[token]) so that no one knows what the actual token is, thus cannot recreate it on another page.
        header('Location: ./login.php');
        exit;
    }

    /* email check */
    $chk_email = $addslashes($_POST['email']);
    $chk_login = $addslashes($_POST['login']);

    //CAPTCHA
    if (isset($_config['use_captcha']) && $_config['use_captcha']==1) {
        $img = new Securimage();
        $valid = $img->check($_POST['secret']);
        if (!$valid)
            $msg->addError('SECRET_ERROR');
    }

    $_POST['password'] = $_POST['form_password_hidden'];
    $_POST['first_name'] = trim($_POST['first_name']);
    $_POST['second_name'] = trim($_POST['second_name']);
    $_POST['last_name'] = trim($_POST['last_name']);

    $_POST['first_name'] = str_replace('<', '', $_POST['first_name']);
    $_POST['second_name'] = str_replace('<', '', $_POST['second_name']);
    $_POST['last_name'] = str_replace('<', '', $_POST['last_name']);


    /* check for special characters */
    if (!(preg_match("/^[a-zA-Z0-9_.-]([a-zA-Z0-9_.-])*$/i", $_POST['login']))) {
        $msg->addError('LOGIN_CHARS');
    } else {
        $sql = "SELECT * FROM %smembers WHERE login='%s'";
        $rows_logins = queryDB($sql, array(TABLE_PREFIX, $chk_login));
        $num_rows_logins = count($rows_logins);

        if ($num_rows_logins != 0) {
            $msg->addError('LOGIN_EXISTS');
        } else {
            $sql = "SELECT * FROM %sadmins WHERE login='%s'";
            $rows_admins = queryDB($sql, array(TABLE_PREFIX, $chk_login));
            $num_rows_admins = count($rows_admins);
            if ($num_rows_admins != 0) {
                $msg->addError('LOGIN_EXISTS');
            }
        }
    }


    /* password check: password is verified front end by javascript. here is to handle the errors from javascript */
    $password_error = $_POST['password_error'];
    if ($password_error && $password_error <> "") {
        $separator = ',';
        $pwd_errors = explode($separator, $password_error);

        foreach ($pwd_errors as $pwd_error) {
            $pwd_error = strip_tags(urldecode($pwd_error));
            if ($pwd_error == "missing_password") {
                $missing_fields[] = _AT('password');
            } else {
                $msg->addError($pwd_error);
            }
        }
    }

    if (!preg_match("/^[a-z0-9\._-]+@+[a-z0-9\._-]+\.+[a-z]{2,6}$/i", $_POST['email'])) {
        $msg->addError('EMAIL_INVALID');
    }
    $sql = "SELECT * FROM %smembers WHERE email='%s'";
    $rows_email = queryDB($sql,array(TABLE_PREFIX, $chk_email));
    $num_rows_email = count($rows_email);

    if ($num_rows_email != 0) {
        $msg->addError('EMAIL_EXISTS');
    } else if ($_POST['email'] != $_POST['email2']) {
        $msg->addError('EMAIL_MISMATCH');
    }

    $_POST['login'] = strtolower($_POST['login']);

    $dob=$_POST['date'];

    unset($master_list_sql);
    if (defined('AT_MASTER_LIST') && AT_MASTER_LIST) {

        $student_id  = $addslashes($_POST['student_id']);
        $student_pin = md5($_POST['student_pin']);

        $sql    = "SELECT member_id FROM %smaster_list WHERE public_field='%s' AND hash_field='%s'";
        $row_master_list = queryDB($sql, array(TABLE_PREFIX, $student_id, $student_pin), TRUE);

        if (!isset($row_master_list['member_id']) || $row_master_list['member_id'] != 0) {
            // the row wasn't found, or it was found but already used
            $msg->addError('REGISTER_MASTER_USED');
        } else {
            $master_list_sql = "UPDATE %smaster_list SET member_id=LAST_INSERT_ID() WHERE public_field='%s' AND hash_field='%s'";
        }
    }

    if($_POST['gender'] == _AT('male'))
        $gender='m';

    if($_POST['gender'] == _AT('female'))
        $gender='f';

    if (($_POST['gender'] != _AT('male')) && ($_POST['gender'] !=  _AT('female')))
    {
        $gender = 'n'; // not specified
    }

    if (!$msg->containsErrors())
    {
        if (($_POST['website']) && (!strstr($_POST['website'],"://")))
        {
            $_POST['website'] = "http://".$_POST['website'];
        }
        if ($_POST['website'] == 'http://')
        {
            $_POST['website'] = '';
        }
        if (isset($_POST['private_email']))
        {
            $_POST['private_email'] = 1;
        } else {
            $_POST['private_email'] = 0;
        }
        $_POST['postal'] = strtoupper(trim($_POST['postal']));

        $_POST['email']      = $addslashes($_POST['email']);
        $_POST['login']      = $addslashes($_POST['login']);
        $_POST['password']   = $addslashes($_POST['password']);
        $_POST['website']    = $addslashes($_POST['website']);
        $_POST['first_name'] = $addslashes($_POST['first_name']);
        $_POST['second_name']= $addslashes($_POST['second_name']);
        $_POST['last_name']  = $addslashes($_POST['last_name']);
        $_POST['address']    = $addslashes($_POST['address']);
        $_POST['postal']     = $addslashes($_POST['postal']);
        $_POST['city']       = $addslashes($_POST['city']);
        $_POST['province']   = $addslashes($_POST['province']);
        $_POST['country']    = $addslashes($_POST['country']);
        $_POST['phone']      = $addslashes($_POST['phone']);



        if (defined('AT_EMAIL_CONFIRMATION') && AT_EMAIL_CONFIRMATION) {
            $status = AT_STATUS_UNCONFIRMED;
        } else {
            $status = AT_STATUS_STUDENT;
        }
        $now = date('Y-m-d H:i:s'); // we use this later for the email confirmation.

        /* insert into the db */
        $sql = "INSERT INTO %smembers
		              (login,
		               password,
		               email,
		               website,
		               first_name,
		               second_name,
		               last_name,
		               dob,
		               gender,
		               address,
		               postal,
		               city,
		               province,
		               country,
		               phone,
		               status,
		               preferences,
		               creation_date,
		               language,
		               inbox_notify,
		               private_email,
		               last_login)
		       VALUES ('$_POST[login]',
		               '$_POST[password]',
		               '$_POST[email]',
		               '$_POST[website]',
		               '$_POST[first_name]',
		               '$_POST[second_name]',
		               '$_POST[last_name]',
		               '$dob',
		               '$gender',
		               '$_POST[address]',
		               '$_POST[postal]',
		               '$_POST[city]',
		               '$_POST[province]',
		               '$_POST[country]',
		               '$_POST[phone]',
		               $status,
		               '$_config[pref_defaults]',
		               '$now',
		               '$_SESSION[lang]',
		               $_config[pref_inbox_notify],
		               $_POST[private_email],
		               '0000-00-00 00:00:00')";


        $result = queryDB($sql, array(TABLE_PREFIX)) or die(at_db_error());
        $m_id	= at_insert_id($db);

        if (!$result)
        {
            $msg->addError('DB_NOT_UPDATED');
            $msg->printAll();
            exit;
        }
        else
        {
            //process any extra fields
            $sql = "SELECT * FROM %sforms";
            $result = queryDB($sql, array(TABLE_PREFIX));

            $column= array();
            $values= array();
            $column[]="`login`";
            $values[]="'$_POST[login]'";
            foreach($result as $row)
            {
                $column[]="`".$row['name']."`";
                $values[]="'".$addslashes($_POST[$row['name']])."'";
            }

            $column= implode(',', $column);
            $values=implode(',', $values);
            $sqlExtra="INSERT INTO %smembers_extra (".$column.") VALUES (".$values.")";
            $result2 = queryDB($sqlExtra, array(TABLE_PREFIX)) or die(at_db_error());

            if (!$result2)
            {
                $msg->addError('DB_NOT_UPDATED');
                $msg->printAll();
                exit;
            }

        }



        if (isset($master_list_sql)) {
            queryDB($master_list_sql, array(TABLE_PREFIX,$student_id, $student_pin));
        }

        //reset login attempts
        if ($result){
            $sql = "DELETE FROM %smember_login_attempt WHERE login='%s'";
            queryDB($sql, array(TABLE_PREFIX, $_POST['login']));
        }

        if (defined('AT_EMAIL_CONFIRMATION') && AT_EMAIL_CONFIRMATION) {
            $msg->addFeedback('REG_THANKS_CONFIRM');

            $code = substr(md5($_POST['email'] . $now . $m_id), 0, 10);

            if (isset($_REQUEST["en_id"]) && $_REQUEST["en_id"] <> "")
                $confirmation_link = $_base_href . 'confirm.php?id='.$m_id.SEP.'m='.$code.SEP.'en_id='.$_REQUEST["en_id"];
            else
                $confirmation_link = $_base_href . 'confirm.php?id='.$m_id.SEP.'m='.$code;

            /* send the email confirmation message: */
            require(AT_INCLUDE_PATH . 'classes/phpmailer/atutormailer.class.php');
            $mail = new ATutorMailer();

            $mail->From     = $_config['contact_email'];
            $mail->AddAddress($_POST['email']);
            $mail->Subject = SITE_NAME . ' - ' . _AT('email_confirmation_subject');
            $mail->Body    = _AT('email_confirmation_message', SITE_NAME, $confirmation_link);
            $mail->Send();

        }
        else
        {
            // if en_id is set, automatically enroll into courses that links with en_id and go to "My Start Page"
            $member_id	= $m_id;

            require (AT_INCLUDE_PATH.'html/auto_enroll_courses.inc.php');

            // update last_login
            $sql = "UPDATE %smembers
			           SET last_login=now(), creation_date=creation_date
			         WHERE member_id=%d";
            queryDB($sql, array(TABLE_PREFIX, $member_id));
            // auto login
            $_SESSION['valid_user'] = true;
            $_SESSION['member_id']	= $m_id;
            $_SESSION['course_id']  = 0;
            $_SESSION['login']		= $_POST[login];
            assign_session_prefs(unserialize(stripslashes($_config[pref_defaults])), 1);
            $_SESSION['is_guest']	= 0;
            $_SESSION['lang']		= $_SESSION[lang];
            session_write_close();

            header('Location: '.AT_BASE_HREF.'bounce.php?course='.$_POST['course']);
        }
        exit;
    }
} else {
    $_POST = array();
}

?>

<?php


include("PFBC/Form.php");
$ml='';
$login='';
$form = new Form("form");
$form->configure(array("action"=>$_base_path .'mods/hello_world/signup.php',"view" => new View\SideBySide(array("classLabels" => array("formAction"=>"row buttons","controlGroup"=>"row","fieldsetLabel"=>"group_form")))));

if(isset($_POST['ml']))
{$ml=$_POST['ml'];}

$form->addElement(new Element\Hidden("ml",$ml,array("id"=>"ml")));
$form->addElement(new Element\Hidden("password_error", "",array("id"=>"password_error")));
$form->addElement(new Element\Hidden("form_password_hidden", "",array("id"=>"form_password_hidden")));
$form->addElement(new Element\Hidden("registration_token",sha1($_SESSION['token'])));

$form->addElement(new Element\HTML('<legend class="group_form">'._AT('required_information').'</legend>'));

if (!isset($_POST['member_id']) && defined('AT_MASTER_LIST') && AT_MASTER_LIST && !admin_authenticate(AT_ADMIN_PRIV_USERS, TRUE))
{
    $form->addElement(new Element\HTML('<h3>'._AT('account_authorization').'</h3>'));
    $form->addElement(new Element\Textbox(_AT('student_id'),"student_id",array("value"=>stripslashes(htmlspecialchars($_POST['student_id'])),"id"=>"student_id","size"=>"15","maxlength"=>"15","required"=>1)));
    $form->addElement(new Element\Password(_AT('student_pin'),"student_pin",array("value"=>stripslashes(htmlspecialchars($_POST['student_pin'])),"id"=>"student_id","size"=>"15","maxlength"=>"15","required"=>1)));
}

$table_title="<div class=\"row\"> <h3>" . _AT('course_to_auto_enroll'). "</h3><small>&middot; " ._AT('auto_enroll_msg')."</small></div>";
require(AT_INCLUDE_PATH.'html/auto_enroll_list_courses.inc.php');


if (isset($_POST['member_id']))
{
    $form->addElement(new Element\Hidden("member_id",intval($_POST['member_id'])));
    $form->addElement(new Element\Hidden("login",(isset($_POST['login']) ? stripslashes(htmlspecialchars($_POST['login'])):"")));
}
else{

    $form->addElement(new Element\Textbox(_AT('login_name'),"login",array("value"=>(isset($_POST['login']) ? stripslashes(htmlspecialchars($_POST['login'])):""),"id"=>"login","size"=>"30","maxlength"=>"20","title"=> _AT('login_name').':'._AT('contain_only'),"required"=>1,"longDesc" =>'<br><small>&middot'._AT('contain_only').'<br/>&middot'. _AT('20_max_chars').'</small>')));

}

if (!admin_authenticate(AT_ADMIN_PRIV_USERS, TRUE) || !$_POST['member_id'])
{
    $form->addElement(new Element\Password(_AT('password'),"form_password1",array("id"=>"form_password1","size"=>"15","maxlength"=>"15","title"=> _AT('password').':'._AT('combination'),"required"=>1,"longDesc" =>'<br><small>&middot'._AT('combination').'<br />&middot'. _AT('15_max_chars').'</small>')));
    $form->addElement(new Element\Password(_AT('password_again'),"form_password2",array("id"=>"form_password2","size"=>"15","maxlength"=>"15","required"=>1)));
}

if (isset($_config['use_captcha']) && $_config['use_captcha']==1 && !$this->no_captcha)
{
    $form->addElement(new Element\Captcha("Captcha",array("required"=>1)));
}

$form->addElement(new Element\Email(_AT('email_address'),"email",array("value"=>(isset($_POST['email']) ? stripslashes(htmlspecialchars($_POST['email'])):""),"id"=>"email","size"=>"30","maxlength"=>"50","required"=>1)));
$form->addElement(new Element\Checkbox("", "private_email", array(_AT('keep_email_private')),array("value"=>(isset($_POST['private_email']) ?$_POST['private_email']:""),"id"=>"priv")));
$form->addElement(new Element\Email(_AT('email_again'),"email2",array("value"=>(isset($_POST['email2']) ? stripslashes(htmlspecialchars($_POST['email2'])):""),"id"=>"email2","size"=>"30","maxlength"=>"50","required"=>1)));
$form->addElement(new Element\Textbox(_AT('first_name'),"first_name",array("value"=>(isset($_POST['first_name']) ? stripslashes(htmlspecialchars($_POST['first_name'])):""),"id"=>"first_name","required"=>1)));
$form->addElement(new Element\Textbox(_AT('second_name'),"second_name" ,array("value"=>(isset($_POST['second_name']) ? stripslashes(htmlspecialchars($_POST['second_name'])):""),"id"=>"second_name" )));
$form->addElement(new Element\Textbox(_AT('last_name'),"last_name" ,array("value"=>(isset($_POST['last_name']) ? stripslashes(htmlspecialchars($_POST['last_name'])):""),"id"=>"last_name","required"=>1)));

if (admin_authenticate(AT_ADMIN_PRIV_USERS, TRUE)){
    if ($_POST['status'] == AT_STATUS_INSTRUCTOR) {
        $stat = _AT('instructor');
    } else if ($_POST['status'] == AT_STATUS_STUDENT) {
        $stat= _AT('student');
    }  else if ($_POST['status'] == AT_STATUS_DISABLED) {
        $stat =  _AT('disabled');
    } else {
        $stat= _AT('unconfirmed');
    }

    $form->addElement(new Element\Hidden("id",$_POST['member_id']));
    if (defined('AT_EMAIL_CONFIRMATION') && AT_EMAIL_CONFIRMATION){
        $form->addElement(new Element\Radio(_AT('account_status'), "status", array( _AT('disabled'), _AT('unconfirmed'),_AT('student'),_AT('instructor')), array("id"=>'status',"required"=>1,"value"=>$stat)));
    }
    else{
        $form->addElement(new Element\Radio(_AT('account_status'), "status", array( _AT('disabled'), _AT('student'),_AT('instructor')), array("id"=>'status',"required"=>1,"value"=>$stat)));
    }
    $form->addElement(new Element\Hidden("old_status",$_POST['old_status']));
}

//optional fields
//add new fieldset for optional inputs
$form->addElement(new Element\HTML('</fieldset><fieldset class="group_form">'));
$form->addElement(new Element\HTML('<legend class="group_form">'._AT('personal_information').' ('._AT('optional').')'.'</legend>'));

//following code relate to another module and needs refactor
$mod = $moduleFactory->getModule('_standard/profile_pictures');
if (admin_authenticate(AT_ADMIN_PRIV_USERS, TRUE) && $_POST['member_id'] && $mod->isEnabled() === TRUE): ?>
<div class="row">
    <?php echo _AT('picture'); ?><br/>
    <?php if (profile_image_exists($_POST['member_id'])): ?>
    <a href="get_profile_img.php?id=<?php echo $_POST['member_id'].SEP.'size=o'; ?>"><?php print_profile_img($_POST['member_id']); ?></a>
    <input type="checkbox" name="profile_pic_delete" value="1" id="profile_pic_delete" />
    <label for="profile_pic_delete"><?php echo _AT('delete'); ?></label>
    <?php else: ?>
    <?php echo _AT('none'); ?> <a href="mods/_standard/profile_pictures/admin/profile_picture.php?member_id=<?php echo $_POST['member_id']; ?>"><?php echo _AT('add'); ?></a>
    <?php endif; ?>
</div>
<?php endif;

if (admin_authenticate(AT_ADMIN_PRIV_USERS, TRUE) && defined('AT_MASTER_LIST') && AT_MASTER_LIST){
    $form->addElement(new Element\Hidden("old_student_id",$_POST['old_student_id']));
    $form->addElement(new Element\Textbox(_AT('student_id'),"student_id",array("value"=>isset($_POST['student_id'])?$_POST['student_id']:"","size"=>"20")));
    $form->addElement(new Element\Checkbox("", "overwrite", array(_AT('overwrite_master')),array("value"=>(isset($_POST['overwrite']) ?$_POST['overwrite']:""),"id"=>"overwrite")));
}

$form->addElement(new Element\Date(_AT('date_of_birth'), "date",array("value"=>(isset($_POST['date']) ? $_POST['date']:""))));
$form->addElement(new Element\Radio(_AT('gender'), "gender", array( _AT('male'), _AT('female'),_AT('not_specified')), array("value"=>(isset($_POST['gender']) ? $_POST['gender']:""),"id"=>'sex')));
$form->addElement(new Element\Textbox(_AT('street_address'),"address",array("value"=>(isset($_POST['address']) ? stripslashes(htmlspecialchars($_POST['address'])):""),"id"=>"address","size"=>"40")));
$form->addElement(new Element\Textbox(_AT('postal_code'),"postal",array("value"=>(isset($_POST['postal']) ? stripslashes(htmlspecialchars($_POST['postal'])):""),"id"=>"postal","size"=>"7")));
$form->addElement(new Element\Textbox(_AT('city'),"city",array("value"=>(isset($_POST['city']) ? stripslashes(htmlspecialchars($_POST['city'])):""),"id"=>"city")));
$form->addElement(new Element\Textbox(_AT('province'),"province",array("value"=>(isset($_POST['province']) ? stripslashes(htmlspecialchars($_POST['province'])):""),"id"=>"province",)));
$form->addElement(new Element\Textbox(_AT('country'),"country",array("value"=>(isset($_POST['country']) ? stripslashes(htmlspecialchars($_POST['country'])):""),"id"=>"country")));
$form->addElement(new Element\Textbox(_AT('phone'),"phone",array("value"=>(isset($_POST['phone']) ? stripslashes(htmlspecialchars($_POST['phone'])):""),"id"=>"phone","size"=>"11")));
$form->addElement(new Element\Textbox(_AT('web_site'),"website",array("value"=>(isset($_POST['website']) ? stripslashes(htmlspecialchars($_POST['website'])):""),"id"=>"website","size"=>"40" )));

//*****************show element using db**************

$sql = "SELECT * FROM %sforms ORDER BY rank";
$result = queryDB($sql, array(TABLE_PREFIX));

foreach($result as $row)
{
    //get the options from the database for the for input type radio,checkbox and select
    if($row['type']=="radio"||$row['type']=="select"||$row['type']=="checkbox")
    {
        $choice= array();
        $sql2 = "SELECT choice FROM %sforms_options WHERE element_id='$row[id]'";
        $result2=queryDB($sql2, array(TABLE_PREFIX)) or die(at_db_error());
        foreach($result2 as $val)
        {
            $choice[]=$val['choice'];
        }
    }
    if($row['required']==1)
    {
        if($row['type']=="radio")
            $form->addElement(new Element\Radio($row['label'], $row['name'],$choice,array("value"=>(isset($_POST[$row['name']]) ? $_POST[$row['name']]:""),"id"=>$row['id'],"required"=>$row['required'])));
        if($row['type']=="select")
            $form->addElement(new Element\Select($row['label'], $row['name'],$choice,array("value"=>(isset($_POST[$row['name']]) ? $_POST[$row['name']]:""),"id"=>$row['id'],"required"=>$row['required'])));
        if($row['type']=="checkbox")
            $form->addElement(new Element\Checkbox($row['label'], $row['name'],$choice,array("value"=>(isset($_POST[$row['name']]) ? $_POST[$row['name']]:""),"id"=>$row['id'],"required"=>$row['required'])));
        if($row['type']=="textarea")
            $form->addElement(new Element\Textarea($row['label'], $row['name'],array("value"=>(isset($_POST[$row['name']]) ? $_POST[$row['name']]:""),"id"=>$row['id'],"required"=>$row['required'])));
        if($row['type']=="country")
            $form->addElement(new Element\Country($row['label'], $row['name'],array("value"=>(isset($_POST[$row['name']]) ? $_POST[$row['name']]:""),"id"=>$row['id'],"required"=>$row['required'])));
        if($row['type']=="password")
            $form->addElement(new Element\Password($row['label'], $row['name'],array("value"=>(isset($_POST[$row['name']]) ? $_POST[$row['name']]:""),"id"=>$row['id'],"required"=>$row['required'])));
        if($row['type']=="date")
            $form->addElement(new Element\Date($row['label'], $row['name'],array("value"=>(isset($_POST[$row['name']]) ? $_POST[$row['name']]:""),"id"=>$row['id'],"required"=>$row['required'])));
        if($row['type']=="textbox")
            $form->addElement(new Element\Textbox($row['label'], $row['name'],array("value"=>(isset($_POST[$row['name']]) ? $_POST[$row['name']]:""),"id"=>$row['id'],"required"=>$row['required'])));
        if($row['type']=="email")
            $form->addElement(new Element\Email($row['label'], $row['name'],array("value"=>(isset($_POST[$row['name']]) ? $_POST[$row['name']]:""),"id"=>$row['id'],"required"=>$row['required'])));
    }
    else
    {
        if($row['type']=="radio")
            $form->addElement(new Element\Radio($row['label'], $row['name'],$choice,array("value"=>(isset($_POST[$row['name']]) ? $_POST[$row['name']]:""),"id"=>$row['id'])));
        if($row['type']=="select")
            $form->addElement(new Element\Select($row['label'], $row['name'],$choice,array("value"=>(isset($_POST[$row['name']]) ? $_POST[$row['name']]:""),"id"=>$row['id'])));
        if($row['type']=="checkbox")
            $form->addElement(new Element\Checkbox($row['label'], $row['name'],$choice,array("value"=>(isset($_POST[$row['name']]) ? $_POST[$row['name']]:""),"id"=>$row['id'])));
        if($row['type']=="textarea")
            $form->addElement(new Element\Textarea($row['label'], $row['name'],array("value"=>(isset($_POST[$row['name']]) ? $_POST[$row['name']]:""),"id"=>$row['id'])));
        if($row['type']=="country")
            $form->addElement(new Element\Country($row['label'], $row['name'],array("value"=>(isset($_POST[$row['name']]) ? $_POST[$row['name']]:""),"id"=>$row['id'])));
        if($row['type']=="password")
            $form->addElement(new Element\Password($row['label'], $row['name'],array("value"=>(isset($_POST[$row['name']]) ? $_POST[$row['name']]:""),"id"=>$row['id'])));
        if($row['type']=="date")
            $form->addElement(new Element\Date($row['label'], $row['name'],array("value"=>(isset($_POST[$row['name']]) ? $_POST[$row['name']]:""),"id"=>$row['id'])));
        if($row['type']=="textbox")
            $form->addElement(new Element\Textbox($row['label'], $row['name'],array("value"=>(isset($_POST[$row['name']]) ? $_POST[$row['name']]:""),"id"=>$row['id'])));
        if($row['type']=="email")
            $form->addElement(new Element\Email($row['label'], $row['name'],array("value"=>(isset($_POST[$row['name']]) ? $_POST[$row['name']]:""),"id"=>$row['id'])));
    }
}

$form->addElement(new Element\Hidden("submit_form", "save"));
$form->addElement(new Element\HTML('</fieldset>'));
$form->addElement(new Element\Button(_AT('save'),"submit",array("name"=>"submit","accesskey"=>"s","onclick"=>"encrypt_password()","class"=>"button")));
$form->addElement(new Element\Button(_AT('cancel'),"submit",array("name"=>"cancel","class"=>"button","onclick"=>"history.go(-1);")));



$form->addElement(new Element\HTML('</fieldset>'));

$form->render();
var_dump($_POST);
//var_dump($result) ;
//var_dump($choice);

?>

<?php require (AT_INCLUDE_PATH.'footer.inc.php'); ?>